---
title: "Analýza historických tenisových dát na predikciu výsledku zápasu"
title-block-banner: true
author: Matúš Gajdoš
format:
  pdf:
    code-fold: true
jupyter: python3
---


# Úvod

V profesionálnom tenise je presné predpovedanie výsledkov zápasov dôležité pre viaceré zainteresované strany, vrátane trénerov, športových analytikov a stávkových spoločností.
Historické údaje o zápasoch poskytujú rozsiahle informácie o výkonnosti hráčov, herných podmienkach a kontexte turnajov, ktoré môžu byť využité na modelovanie a predikciu budúcich výsledkov zápasov.

Cieľom tohto projektu je analyzovať historické údaje o tenisových zápasoch s cieľom predpovedať výsledok zápasu, konkrétne víťazstvo alebo prehru hráča, pomocou dátovo riadených metód a strojového učenia.

# Hlavné otázky

Tento projekt sa snaží odpovedať na nasledujúce kľúčové otázky:

* Ktoré historické a kontextové faktory súvisiace s hráčmi a zápasmi majú najväčší vplyv na výsledok zápasu?

* Do akej miery dokážu historické dáta presne predpovedať víťaza zápasu pred jeho odohraním?

* Aký je prínos jednotlivých typov atribútov (rebríček, vek, povrch, forma) k celkovej predikčnej presnosti modelu?

* Je možné vytvoriť model, ktorý poskytuje nielen presné, ale aj interpretovateľné predikcie výsledkov zápasov?

# Kritériá úspešnosti

Projekt bude považovaný za úspešný, ak:

* Identifikuje kľúčové faktory ovplyvňujúce výsledok tenisového zápasu

* Vytvorí prediktívny model, ktorý:
  + Dosahuje lepšie výsledky než jednoduchý baseline model
  + Poskytuje interpretovateľné a konzistentné predikcie

* Preukazuje praktickú využiteľnosť prostredníctvom metrík, ako:
  + Presnosť, log_loss a F1-score
  + Stabilný výkon naprieč rôznymi zápasmi

# Postup

### Analýza dát

V tejto fáze sa skúma štruktúra tenisových dát, dostupné atribúty a ich základné štatistické vlastnosti.
Cieľom je identifikovať relevantné premenné pre predikciu výsledkov a odhaliť možné problémy v dátach, ako sú chýbajúce alebo nevyvážené hodnoty.

### Predspracovanie dát

Dáta sa vyčistia, transformujú a pripravia na modelovanie, pričom sa vytvára cieľová premenná reprezentujúca result (výhra hráča).
Zároveň sa rieši doplnenie chýbajúcich hodnôt, vytváranie nových príznakov, tranformácia datasetu a kódovanie kategórií.

### Modelovanie a Evaluácia

Na predikciu výsledkov sa aplikujú vybrané klasifikačné algoritmy a porovnávajú sa s jednoduchým baseline modelom.
Modely sú trénované výhradne na predzápasových údajoch a dôraz sa kladie aj na interpretovateľnosť výsledkov.

Modely sa hodnotia pomocou metrík, najmä precision, log loss a F1-score pre triedu výsledkov.
Výsledky sa porovnávajú s baseline prístupom a analyzuje sa, v akých situáciách model dokáže úspešne identifikovať výsledkok zápasu.

# Analýza dát

V tejto časti sa zameriavam na analýzu vstupných dat.
Data pozostavajú z viacerých datasetov (všetky vo formáte csv súboru) z rôznych rokov tenisových ATP turnajov (zaoberám sa teda mužskými zápasmi).
Tieto dáta najskôr korektne spojím do jedného väčšieho datasetu, s ktorým následne budem pracovať.
Jednotlivé identifikátory z rôznych datasetov sú korektne spracované a nevznikajú žiadne konflikty.
Podrobný popis jednotlivých atribútov je uvedený nižšie. 

| **Atribút**          | **Popis**                                                           | **Dátový typ** |
| -------------------- | ------------------------------------------------------------------- | -------------- |
| `tourney_id`         | Jedinečný identifikátor turnaja, kde prvé štyri znaky označujú rok. | object         |
| `tourney_name`       | Názov turnaja.                                                      | object         |
| `surface`            | Povrch kurtu, na ktorom sa turnaj odohráva.                         | object         |
| `draw_size`          | Počet hráčov v hlavnom pavúku turnaja.                              | int64          |
| `tourney_level`      | Úroveň turnaja vyjadrená kódom podľa okruhu (ATP/WTA/ITF).          | object         |
| `tourney_date`       | Dátum začiatku turnaja vo formáte YYYYMMDD.                         | int64          |
| `match_num`          | Identifikátor zápasu v rámci turnaja.                               | int64          |
| `winner_id`          | Jedinečný identifikátor víťaza zápasu.                              | int64          |
| `winner_seed`        | Nasadenie víťaza na turnaji.                                        | float64        |
| `winner_entry`       | Spôsob vstupu víťaza do turnaja (napr. WC, Q, LL).                  | object         |
| `winner_name`        | Meno víťaza zápasu.                                                 | object         |
| `winner_hand`        | Dominantná ruka víťaza (R, L alebo U).                              | object         |
| `winner_ht`          | Výška víťaza v centimetroch.                                        | float64        |
| `winner_ioc`         | Trojznakový kód krajiny víťaza.                                     | object         |
| `winner_age`         | Vek víťaza v rokoch v čase turnaja.                                 | float64        |
| `loser_id`           | Jedinečný identifikátor porazeného hráča.                           | int64          |
| `loser_seed`         | Nasadenie porazeného hráča.                                         | float64        |
| `loser_entry`        | Spôsob vstupu porazeného hráča do turnaja.                          | object         |
| `loser_name`         | Meno porazeného hráča.                                              | object         |
| `loser_hand`         | Dominantná ruka porazeného hráča.                                   | object         |
| `loser_ht`           | Výška porazeného hráča v centimetroch.                              | float64        |
| `loser_ioc`          | Trojznakový kód krajiny porazeného hráča.                           | object         |
| `loser_age`          | Vek porazeného hráča v rokoch.                                      | float64        |
| `score`              | Konečný výsledok zápasu po setoch.                                  | object         |
| `best_of`            | Maximálny počet setov v zápase (3 alebo 5).                         | int64          |
| `round`              | Kolo turnaja, v ktorom sa zápas odohral.                            | object         |
| `minutes`            | Dĺžka zápasu v minútach.                                            | float64        |
| `w_ace`              | Počet es víťaza.                                                    | float64        |
| `w_df`               | Počet dvojchýb víťaza.                                              | float64        |
| `w_svpt`             | Počet bodov pri podaní víťaza.                                      | float64        |
| `w_1stIn`            | Počet úspešných prvých podaní víťaza.                               | float64        |
| `w_1stWon`           | Počet bodov vyhraných po prvom podaní víťaza.                       | float64        |
| `w_2ndWon`           | Počet bodov vyhraných po druhom podaní víťaza.                      | float64        |
| `w_SvGms`            | Počet gemov na podaní víťaza.                                       | float64        |
| `w_bpSaved`          | Počet odvrátených brejkbalov víťaza.                                | float64        |
| `w_bpFaced`          | Počet brejkbalov, ktorým víťaz čelil.                               | float64        |
| `l_ace`              | Počet es porazeného hráča.                                          | float64        |
| `l_df`               | Počet dvojchýb porazeného hráča.                                    | float64        |
| `l_svpt`             | Počet bodov pri podaní porazeného hráča.                            | float64        |
| `l_1stIn`            | Počet úspešných prvých podaní porazeného hráča.                     | float64        |
| `l_1stWon`           | Počet bodov vyhraných po prvom podaní porazeného hráča.             | float64        |
| `l_2ndWon`           | Počet bodov vyhraných po druhom podaní porazeného hráča.            | float64        |
| `l_SvGms`            | Počet gemov na podaní porazeného hráča.                             | float64        |
| `l_bpSaved`          | Počet odvrátených brejkbalov porazeného hráča.                      | float64        |
| `l_bpFaced`          | Počet brejkbalov, ktorým porazený hráč čelil.                       | float64        |
| `winner_rank`        | Rebríčkové umiestnenie víťaza v čase turnaja.                       | float64        |
| `winner_rank_poin`   | Počet rebríčkových bodov víťaza.                                    | float64        |
| `loser_rank`         | Rebríčkové umiestnenie porazeného hráča v čase turnaja.             | float64        |
| `loser_rank_poin`    | Počet rebríčkových bodov porazeného hráča.                          | float64        |


Pre predstavu príklad jedného záznamu:

 | tourney_id | surface | draw_size | tourney_level | ... | tourney_date | match_num | loser_rank |
 | ---------- | ------- | --------- | ------------- | --- | ------------ | --------- | ---------- |
 | 2015-339   | Hard    | 28        | A             | ... | 20150104     | 1         | 220        |

Dáta teda zahŕňajú popis jednotlivých turnajov a zápasov, kde sú obsiahnuté podania, počet bodov atď.
Nedisponujú napríklad výhrou konkrétneho bodu v danom zápase.

### Základné charakteristiky dát: 

* Časový rozsah dát: 2015-2023

* Zdroj dát: verejne dostupné historické tenisové štatistiky

* Dáta sú na úrovni jednotlivých zápasov

* 49 atribútov a 26920 počet záznamov

* 93041 chýbajúcich hodnôt (7,9%)

* 7 textových, 8 kategorických a 34 numerických atribútov

* Počet duplicitných hodnôt 2941

### Konzistencia

Cieľom je overiť, či jednotlivé veci nie sú reprezentované inými hodnotami.

V prvom rade biele znaky. Môžu poškodiť konzistenciu ak sa nachádzajú za, pred alebo medzi jednotlivými hodnotami.
```{python}
#| label: fig-table-whitespace
#| fig-cap: "Tabuľka s bielymi znakmi"
#| echo: false
import pandas as pd

df_atp_15 = pd.read_csv("atp_matches_2015.csv")
df_atp_16 = pd.read_csv("atp_matches_2016.csv")
df_atp_17 = pd.read_csv("atp_matches_2017.csv")
df_atp_18 = pd.read_csv("atp_matches_2018.csv")
df_atp_19 = pd.read_csv("atp_matches_2019.csv")
df_atp_20 = pd.read_csv("atp_matches_2020.csv")
df_atp_21 = pd.read_csv("atp_matches_2021.csv")
df_atp_22 = pd.read_csv("atp_matches_2022.csv")
df_atp_23 = pd.read_csv("atp_matches_2023.csv")

datasets = [df_atp_15,df_atp_16,df_atp_16,df_atp_17,df_atp_18,df_atp_19, df_atp_20, df_atp_21, df_atp_22, df_atp_23]

df_final = pd.concat(datasets)
df_final=df_final.drop_duplicates()
df_final=df_final.reset_index(drop=True)

string_cols = df_final.select_dtypes(include="object").columns

import re

whitespace_report = {}

for col in string_cols:
    s = df_final[col].dropna()

    whitespace_report[col] = {
        "leading_ws": s.str.match(r"^\s+").sum(),
        "trailing_ws": s.str.match(r".*\s+$").sum(),
        "multiple_internal_ws": s.str.contains(r"\s{2,}").sum(),
        "tabs_or_nbsp": s.str.contains(r"[\t\u00A0]").sum(),
    }

whitespace_report = pd.DataFrame(whitespace_report).T

problem_cols = whitespace_report[
    whitespace_report.sum(axis=1) > 0
]

problem_cols.sort_values(by=problem_cols.columns.tolist(), ascending=False)


```

V tabuľke [-@fig-table-whitespace] sú zobrazené problémové atribúty a počet problémových hodnôt.
Tieto nekonzistencie vyriešime odstránením bielych znakov, aby odpovedala ostatným hodnotám.

V touney_name je nekonsistencia v mestách, kde sa turnaj odohráva.
Zatiaľ, čo pri väčšine názvov je uvedené mesto alebo podrobná identifikácia, existujú turnaje, ktoré majú rovnaké id líšiace sa rokom a reprezentované rôznými tourney_id.
```{python}
#| echo: false

names = ["Adelaide 1", "Adelaide 2", "Belgrade 2", "Cologne 1", "Cologne 2"]

subset = df_final[df_final["tourney_name"].isin(names)]

tourney_map = (
    subset.groupby("tourney_name")["tourney_id"]
          .unique()
)

pretty_df = (
    tourney_map
    .explode()
    .reset_index()
    .rename(columns={"tourney_id": "tourney_id"})
    .sort_values(["tourney_name", "tourney_id"])
)

print(pretty_df.to_string(index=False))
```

Ďalšie nekonzistencia vzniká pri hráčovi a jeho unikátnym match_num identifikátorom.
Ako je zobrazené nižšie (po dôkladnej inšpekcií, či sa nejedná o dvoch rôznych hráčov) je jeden hráč s dvoma rôznymi identifikátormi.
```{python}
#| echo: false
players = pd.concat([
    df_final[["winner_id", "winner_name"]]
        .rename(columns={"winner_id": "player_id", "winner_name": "player_name"}),
    df_final[["loser_id", "loser_name"]]
        .rename(columns={"loser_id": "player_id", "loser_name": "player_name"}),
])
players["player_name"] = players["player_name"].str.strip()

name_to_id = players.groupby("player_name")["player_id"].nunique()

violations = name_to_id[name_to_id > 1]

problem_players = (
    players[players["player_name"].isin(violations.index)]
      .drop_duplicates()
      .sort_values("player_name")
)

print(problem_players.to_string(index=False))

```

Ďalej pri winner_entry je ALT vyjadrená aj ako Alt.

Pri hráčoch a ich dominantnej ruke je takisto nekonzistencia.
Primárne sa líšia hodnoty od U (unknown) a práve dominantnej ruky.
Preto ak pri hráčovi je známa ruka známa, odstránime U.
```{python}
#| echo: false
#| label: fig-table-hand
#| fig-pos: 'H'
#| fig-cap: "Graf s dominantnou rukou hráčov"
df=df_final.copy()
players = pd.concat([
    df[["winner_id", "winner_hand"]].rename(
        columns={"winner_id": "player_id", "winner_hand": "player_hand"}
    ),
    df[["loser_id", "loser_hand"]].rename(
        columns={"loser_id": "player_id", "loser_hand": "player_hand"}
    ),
])

players["player_hand"] = players["player_hand"].str.upper().str.strip()

hands_per_player = players.groupby("player_id")["player_hand"].unique().apply(list)

ambiguous = hands_per_player[hands_per_player.apply(lambda x: "U" in x and len(x) > 1)]


from collections import Counter

ambiguous_str = ambiguous.apply(lambda x: ''.join(sorted(x)))
counts = Counter(ambiguous_str)

import matplotlib.pyplot as plt

labels = list(counts.keys())
values = list(counts.values())

plt.figure(figsize=(6,4))
bars = plt.bar(labels, values, color=['skyblue', 'orange'])
plt.xlabel("Kombinácia rúk")
plt.ylabel("Počet hráčov")

for bar in bars:
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height()+0.5, str(int(bar.get_height())), 
             ha='center', fontsize=10)

plt.show()
```

Po dôkladnej analýze jednotlivých atribútov a pri ich spojení, ktoré sú spolu súvisiace neboli nájdené žiadne iné nekonzistencie.

### Sanity check

Cieľom sanity checku je overiť zmysluplnosť jednotlivých hodnôt atribútov vzhľadom na to, čo majú vyjadrovať.
Preto overíme hodnoty a budeme identifikovať, či správne odpovedajú realite.
Príkladom môže byť vek, kde očakávame kladné hodnoty a zároveň vyššie ako povedzme 10 rokov.
Bolo by zvláštne, keby hralo tenisový zápas dvojročné dieťa na takto vysokej úrovni.

Pri menách hráčov je hráč s číslom v mene (Alejandro Gomez Gb42).
Po dohladaní sa jedná o chybu.

Pri hráčoch je vek desatinné číslo. Nejedná sa o chybu, ale zaokrúhlime na celé.
Inak vek odpovedá správnym hodnotám, neobjavujú sa chyby.

Pri minutách zápasu sú takisto správne hodnoty. 
Podozrenie môže priťahovať hodnota 0, ktorá sa v dátach vyskytuje, ale je to možný scénar, kedy sa hráč zraní pred zápasom a podobne.

Po overení jednotlivých hodnôt pri každom atribúte, kde boli skúmané negatívne hodnoty pri číselných atribútoch, nezmyselné kódy krajín, povrchu atď. neboli nájdené žiadne nezmyseľné hodnoty.


### Chýbajúce hodnoty

V tejto časti sú rozoberané chýbajúce hodnoty jednotlivých príznakov.
Ako je vidieť na grafe [-@fig-graph-nan] pozorujeme, že pri niektorých príznakoch chýba hodnota až v 75% z celkových dátových záznamov.
Tieto príznaky (winner_seed, winner_entry, loser_seed, loser_entry) teda zahodíme, bolo by to náročné nahradiť vhodne chýbajúce hodnoty, keď nemáme dostatok nechýbajúcich hodnôt, ktoré by nám pomohly pri doplnení napríklad KNN modelom.
Zároveň hodnoty winner_seed sú v určitom kontexte zohľadnené v rankingu.
Každý záznam obsahuje chýbajúcu hodnotu, takže mazanie jednotlivých záznamov nie je korektné.

Z grafu [-@fig-graph-nan] je možné vidieť rovnaký počet pri niektorých príznakoch.
Je to spôsobené tým, že jednotlivé turnaje počas plynulých rokov nedisponujú týmito informáciami, preto je počet rovnaký.
```{python}
#| echo: false
#| label: fig-graph-nan
#| fig-pos: 'H'
#| fig-cap: "Graf s chýbajúcimi hodnotami"
missing_counts = df.isna().sum()
missing_counts = missing_counts[missing_counts > 0].sort_values()

plt.figure(figsize=(10, 6))
plt.barh(missing_counts.index, missing_counts.values)

plt.xlabel("Počet chýbajúcich hodnôt")
plt.ylabel("Atribút")

# Annotate counts
for i, v in enumerate(missing_counts.values):
    plt.text(v, i, str(v), va="center")

plt.tight_layout()
plt.show()

```

Na doplnenie chýbajúcich hodnôt je použitý KNNImputer.
Je to sofistikovanejšia metóda, ako pridanie priemeru.
Môže lepšie zohladňovať jednotlivé počty vyhratých bodov a podobne na základe napríklad rankingu.

### Datové typy

Na začiatku tejto kapitoly je uviedená tabuľka s atribútmi a ich datovými typmi.
Jednotlivé atribúty sú reprezentované správne, kde ale je možná zmena je pri numerických hodnotách, kde väčšinou je uvedený float.
Pritom hodnoty sú, s výnimkou veku, celé čísla.
V tomto duchu sa pozrieme na jednotlivé typy a pripravíme dataset v sekcií predspracovania dát, kde sa hlbšie ponoríme do ich vhodnej reprezentácie. 


### Závislosti

Pozrieme sa na určité príznaky, ktoré by mohli priamo ovplyňovať výsledok zápasu.
Prvým takýmto príznakom je rank hráča. Chcem zistiť, či vyšší rank je istou zárukou víťazstva.

```{python}
#| echo: false
#| label: fig-graph-rank
#| fig-pos: 'H'
#| fig-cap: "Graf rankingu voči výhre"
df_rank = df.dropna(subset=["winner_rank", "loser_rank"]).copy()

df_rank["rank_diff_win"] = df_rank["loser_rank"] - df_rank["winner_rank"]
df_rank["better_ranked_won"] = df_rank["rank_diff_win"] > 0

df_win = df_rank.sort_values("rank_diff_win")
df_win["cum_win_rate"] = df_win["better_ranked_won"].expanding().mean()

df_rank["rank_diff_lose"] = df_rank["winner_rank"] - df_rank["loser_rank"]
df_rank["better_ranked_lost"] = df_rank["rank_diff_lose"] > 0

df_lose = df_rank.sort_values("rank_diff_lose")
df_lose["cum_lose_rate"] = df_lose["better_ranked_lost"].expanding().mean()
fig, axes = plt.subplots(2, 1, figsize=(10,8), sharey=True)

axes[0].plot(df_win["rank_diff_win"], df_win["cum_win_rate"])
axes[0].axhline(0.5, linestyle="--")
axes[0].axvline(0, linestyle="--")
axes[0].set_title("Favorit")
axes[0].set_xlabel("Rozdiel v rankingoch (porazený − víťaz)")
axes[0].set_ylabel("Pravdepodobnosť výhry lepšieho rankingu")

axes[1].plot(df_lose["rank_diff_lose"], df_lose["cum_lose_rate"])
axes[1].axhline(0.5, linestyle="--")
axes[1].axvline(0, linestyle="--")
axes[1].set_title("Outsider")
axes[1].set_xlabel("Rozdiel v rankingoch (víťaz − porazený)")
axes[1].set_ylabel("Pravdepodobnosť výhry horšieho rankingu")


plt.suptitle("Effect of Rank Advantage on Match Outcome", fontsize=14)
plt.tight_layout()
plt.show()
```

V grafov [-@fig-graph-rank] sú vykreslené pravdepodobnosti hráčov na základe ich rozdielu v rankoch.
Môžme vidieť, že keď má víťaz lepší rank, tak s rastúcim rozdielom rankov (osa x) sa zvyšuje pravdepodobnosť, že vyhrá.
Výsledná pravdepodobnost dosahuje okolo 67%, avšak treba si povšimnúť, že menšie rozdiely v rankingoch, v jednotkách až desiatkách nie sú relevantné, pretože pravdepodobnosť výhry nedosahuje ani 50%.

```{python}
#| echo: false
#| label: fig-nieco
#| fig-pos: 'H'
#| fig-cap: "Graf rankingu voči výhre (priblížené)"
fig, axes = plt.subplots(figsize=(7,4))

df_win["rank_diff_win"]=df_win[df_win["rank_diff_win"] < 100]["rank_diff_win"]
df_win["rank_diff_win"]=df_win[df_win["rank_diff_win"] > 0]["rank_diff_win"]

axes.plot(df_win["rank_diff_win"], df_win["cum_win_rate"])
axes.axhline(0.5, linestyle="--")
axes.axvline(0, linestyle="--")
axes.set_title("Favorit")
axes.set_xlabel("Rozdiel v rankingoch (porazený − víťaz)")
axes.set_ylabel("Pravdepodobnosť výhry lepšieho rankingu")
plt.tight_layout()
plt.show()
```

Z bližšieho pohľadu [-@fig-nieco] je vidieť, že až po prekročení rozdielu v rankingoch v hodnote okolo 55 rebríčkov, prekročíme 50% hranicu. 

Na druhú stranu, takzvaný prekvapivý zápas, kde outsider (z pohľadu rankingu) vyhrá sa deje v tretine prípadov, čím si sú rankingovo bližší.

Z dát je možné pozorovať rôzne vplyvy jednotlivých príznakov (napríklad úspešnosť prvého podania) na víťaza zápasu.
Prepokladáme, že prvé podanie je v plnej sile, aby následný return postavil podávajúceho do výhodnejšej pozície.
Pri pohľade na graf [-@fig-service] je patrné, že víťazi zápasu majú vyššiu úspešnosť vyhratých bodov po prvom podaní (približne o 10%).
```{python}
#| echo: false
#| label: fig-service
#| fig-pos: 'H'
#| fig-cap: "Rozdelenie úspešnosti prvého podania"
import numpy as np

cols = ["w_1stIn", "w_1stWon", "l_1stIn", "l_1stWon"]
df_fs = df.dropna(subset=cols).copy()

df_fs["w_1st_win_rate"] = df_fs["w_1stWon"] / df_fs["w_1stIn"]
df_fs["l_1st_win_rate"] = df_fs["l_1stWon"] / df_fs["l_1stIn"]

df_fs = df_fs.replace([np.inf, -np.inf], np.nan)
df_fs = df_fs.dropna(subset=["w_1st_win_rate", "l_1st_win_rate"])

plt.figure(figsize=(8,5))

plt.hist(df_fs["w_1st_win_rate"], bins=50, alpha=0.6, label="Víťaz")
plt.hist(df_fs["l_1st_win_rate"], bins=50, alpha=0.6, label="Porazený", color="orange")

plt.xlabel("Úspešnosť vyhratých bodov po prvom podaní (%)")
plt.ylabel("Počet zápasov")
plt.legend()
plt.tight_layout()
plt.show()
```

Avšak pred zápasom tieto dáta zo zápasu nemáme a teda pri predikcií víťaza sa sústredíme na dáta, ktoré budeme pred zápasom poznať.
Na tieto hodnoty sa pozrieme v predspacovaní, kde sa tomu podrobnejšie venujem.

# Predspracovanie dát

V tejto časti upravíme dataset do požadovanej formy tak, aby sme nad ním mohli následne modelovať.
V prvok kroku prevedieme zmeny, ktoré boli spomenuté pri analýze.
Konkrétne odstránime nekonzistencie, nezmyselné hodnoty, vysporiadame sa s chýbajúcimi hodnotami a upravíme datové typy.
```{python}
#| echo: false

import pandas as pd

df=pd.read_csv("transformed_augmented.csv")

drop_cols=['match_num', 'score', 'minutes', 'player_1_ace', 'player_1_df', 'player_1_svpt', 'player_1_1stIn',
       'player_1_1stWon', 'player_1_2ndWon', 'player_1_SvGms',
       'player_1_bpSaved', 'player_1_bpFaced', 'player_2_ace', 'player_2_df',
       'player_2_svpt', 'player_2_1stIn', 'player_2_1stWon', 'player_2_2ndWon',
       'player_2_SvGms', 'player_2_bpSaved', 'player_2_bpFaced', "is_final","p1_age","p2_age", "p1_ht", "p2_ht","p1_rank","p2_rank"]



df = df.drop(drop_cols,axis=1)
df["player_1_rank"] = df["player_1_rank"].round()
df["player_2_rank"] = df["player_2_rank"].round()
df["player_1_age"] = df["player_1_age"].round().astype("Int64")
df["player_2_age"] = df["player_2_age"].round().astype("Int64")
obj_cols = df.select_dtypes(include=['object']).columns.tolist()
for c in obj_cols:
    try:
        df[c] = df[c].astype('category').cat.codes
    except Exception:
        pass

float_cols = df.select_dtypes(include=['float']).columns.tolist()
for c in float_cols:
    s = pd.to_numeric(df[c], errors='coerce')
    non_na = s.dropna()
    if non_na.empty:
        df[c] = s.astype('Int64')
        continue
    if (non_na % 1 == 0).all():
        df[c] = s.round(0).astype('Int64')
    else:
        df[c] = s.astype(float)

for col in ['p1_win_streak','p2_win_streak','p1_lose_streak','p2_lose_streak','p1_titles','p2_titles']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype('Int64')

for col in ['p1_surface_wr','p2_surface_wr']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0.0).astype(float)
```

Následne bude naším cielom vytvoriť nové príznaky, ktoré by potenciálne mohli byť pri modelovaní užitočné (príklad rozdiel v rankingu).

Záverom tejto časti je transformovaný dataset, ktorý je pripravený na modelovanie.

### Transformácia

Pôvodný dataset chcem pripraviť na modelovanie, to znamená, že nemôže obsahovať metriky zápasov, ako napríklad počet es, dvojchýb, bodov po prvom podaní atď.
Takýmito hodnotami pri predikcií, či daný hráč vyhrá zápas nedisponujeme a budeme sa snažiť zistiť výhercu, čisto na dátach z minulosti.
Preto upravýme dataset do formy, kde jednotlivé štatistiky zo zápasu odstránime.

Takisto vhodná reprezentácia dát je potrebná, a preto jednotlivé príznaky transformujeme do vhodného formátu.
Čísla, ktoré sú celé reprezentujeme, ako int: vek (zaokruhlené), rank (zaokruhlené), tourney_id, winner_id atď.

Floaty sú napríklad winner_ht, loser_ht, winner_rank_points.

Modely nedokážu pracovať s kategorickými dátami reprezentované stringom.
Tieto príznaky, ako meno hráčov, turnajov, povrchu, či iných zakódujeme jednoducho do číselnej podoby, kde každej hodnote priradí svoj identifikátor.

Ďalšia dôležitá tranformácia spočíva v tom, že si dáta namiesto winner a loser pretransformujeme do player_1 a player_2.
Dôvodom je, aby sme vedeli skonštruovať vysvetlovanú premennú result (binárna hodnota), ktora vyjadruje, či player_1 vyhral alebo nie.

Po tejto tranformácií sme schopný korektne modelovať nad vysvetlovanou premennou.
Hodnoty sú číselné a jednotlivé modely s nimi budú vedieť pracovať. 

### Nové príznaky

***p1_win_streak, p2_win_streak***

Pre každého hráča skonštruujem takzvaný win streak (int).
Je to celé číslo, ktoré reprezentuje počet vyhratých zápasov v rade podľa dátumu zápasu.

***p1_lose_streak, p2_lose_streak***

Pre každého hráča skonštruujem lose streak (int).
Je to celé číslo, ktoré reprezentuje počet prehratých zápasov v rade podľa dátumu zápasu.

***p1_surface_wr, p2_surface_wr***

p1_surface_wr je atribút, ktoré reprezentuje percento vyhratých zápasov na povrchu, na ktorom sa aktuálny zápas hrá (float).
Takisto je príznak skonštruovaný iba na predošlých zápasoch.


***p1_titles, p2_titles***

Počet vyhratých turnajov do aktuálneho zápasu.

***rank_diff, rank_diff_abs, rank_rel***

Po rade odpovedajúce vyššie uvedenému.
Rozdieľ hráčov v rankingu vo forme player_1_rank - player_2_rank (int), absolútna hodnota rozdielu rankingu (int) a relatívna hodnota rankingu vypočítaná následovne rank_diff/(player_1_rank + player_2_rank) (float).

***age_diff, height_diff, win_streak_diff, lose_streak_diff, surface_wr_diff, titles_diff***

Všetky príznaky znamenajú rozdiel medzi dvoma atribútmi.
Poporade je to vek (int), výška hráčov (float), win_streak (int), lose_streak (int), surface_wr (float), titles (int).


# Modelovanie a Evaluácia

Po fáze predspracovania je k dispozícii výsledný dataset v požadovanom formáte. Dataset obsahuje výhradne numerické atribúty a neobsahuje žiadne chýbajúce hodnoty, čo umožňuje jeho priame použitie v modelovacích algoritmoch. V tejto časti sa zameriavame na modelovanie a predikciu výsledku tenisového zápasu na základe informácií dostupných ešte pred jeho odohraním.

Najskôr je vykonaná analýza korelácie jednotlivých atribútov. 
Na obrázku [-@fig-correlation-between-features] je znázornená korelačná matica, ktorá ilustruje vzťahy medzi príznakmi v datasete.
Je zrejmé, že niektoré atribúty, napríklad rank a rank_points, vykazujú silnú vzájomnú koreláciu, čo je očakávané, keďže rebríčkové umiestnenie je priamo odvodené od počtu získaných bodov. Rovnako možno pozorovať zvýšenú koreláciu medzi novovytvorenými príznakmi, ktoré sú koncepčne navzájom prepojené.
```{python}
#| echo: false
#| label: fig-correlation-between-features
#| fig-pos: 'H'
#| fig-cap: "Korelačná matica príznakov"

# 1. Standard Library
import random
from tqdm import tqdm

# 2. Data Manipulation & Numerical Computing
import numpy as np
import pandas as pd

# 3. Machine Learning & Preprocessing
import xgboost as xgb
import shap
from sklearn.model_selection import train_test_split, GridSearchCV, TimeSeriesSplit
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    log_loss,
    brier_score_loss,
    f1_score,
    classification_report,
    confusion_matrix
)

# 4. Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

df = pd.read_csv('final.csv')

# Calculate the correlation matrix
correlation_matrix = df.corr(method='spearman')

# Set the size of the plot
plt.figure(figsize=(8, 6))

# Create the heatmap
sns.heatmap(
    correlation_matrix,
    annot=False,
    cmap='coolwarm',
    fmt=".2f",
    linewidths=.5,
    cbar=True
)

#plt.title('Feature Correlation Matrix')
plt.show()

```

V ďalšom kroku je analyzovaný vzťah jednotlivých príznakov k vysvetľovanej premennej, ktorou je výsledok zápasu.
Nižšie sú uvedené príznaky s najsilnejšou koreláciou k cieľovej premennej.
Tieto atribúty predstavujú dôležité vstupy pre následné modelovanie, najmä v prípade logistickej regresie, kde koeficienty modelu priamo odrážajú ich vplyv na pravdepodobnosť výhry.
```{python}
#| echo: false
#| fig-pos: 'H'

# Get the correlations of all features against 'Price'
result_correlations = correlation_matrix['result'].sort_values(ascending=False)

print(result_correlations[:8])
print(result_correlations[-5:])
```

Ako jednoduchý baseline model je použitý náhodný klasifikátor, ktorý simuluje hádzanie mincou.
Dataset je najskôr rozdelený na trénovaciu a testovaciu množinu v časovom poradí, aby sa zachovala chronologická konzistentnosť dát.
Následne je vyhodnotená presnosť tohto náhodného modelu, ktorá slúži ako minimálna úroveň výkonu, ktorú musia sofistikovanejšie modely prekonať.
```{python}
#| echo: false
#| fig-pos: 'H'

df_sorted = df.sort_values(by='tourney_date').copy()
df_sorted.reset_index(drop=True, inplace=True)

X = df.drop('result', axis=1)
y = df['result']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)


coin_flip = []
for i in range(len(y_test)):
  coin_flip.append(random.choice([0,1]))

y_test_arr = np.array(y_test)

accurate = 0

for i in range(len(y_test_arr)):
  if y_test_arr[i] == coin_flip[i]:
    accurate += 1

print(f'Presnoť: {accurate / len(y_test_arr):.2f}')

```

Pre ďalšie testovanie modelov, konkrétne logistickej regresie a algoritmu XGBoost, je použitá krížová validácia s časovým rozdelením dát.
Trénovacia a testovacia množina sú rozdelené do viacerých podmnožín pomocou metódy TimeSeriesSplit, ktorá zabezpečuje, že model je vždy trénovaný na historických dátach a testovaný na novších pozorovaniach pričom bolo zachované časové poradie zápasov, aby sa predišlo úniku informácií z budúcnosti do minulosti.
Tento prístup lepšie simuluje reálne použitie modelu v praxi, kde sú predikcie vždy založené na historických údajoch.
```{python}
#| echo: false
#| fig-pos: 'H'

# This is how are the data split for testing

tscv = TimeSeriesSplit(n_splits=10)

for i, (train_index, test_index) in enumerate(tscv.split(X_test)):
    print(f"Fold {i}:")
    print(f"  Train: index {train_index[0]} to {train_index[-1]}")
    print(f"  Test:  index {test_index[0]} to {test_index[-1]}")

```

Na samotné modelovanie sú použité dva prístupy.
Logistická regresia predstavuje lineárny klasifikačný model, ktorý umožňuje jednoduchú interpretáciu vplyvu jednotlivých príznakov na výsledok zápasu.
Algoritmus XGBoost je naopak pokročilý stromový model založený na gradientnom posilňovaní, ktorý kombinuje veľké množstvo slabých rozhodovacích stromov a postupne optimalizuje chyby predchádzajúcich modelov.
Na ladenie hyperparametrov oboch modelov je použitá metóda GridSearchCV, ktorá umožňuje systematické vyhľadanie optimálnej konfigurácie modelu.

```{python}
#| echo: false
#| fig-pos: 'H'

# 1. Setup Data
X = df_sorted.drop('result', axis=1)
y = df_sorted['result']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# --- 2. METRICS FUNCTION ---
def get_metrics(y_true, y_probs, threshold=0.5):
    y_pred = (y_probs >= threshold).astype(int)
    return {
        'accuracy': accuracy_score(y_true, y_pred),
        'log_loss': log_loss(y_true, y_probs),
        'f1': f1_score(y_true, y_pred),
        'threshold': threshold
    }


# 2. Define the TimeSeriesSplit
# This creates folds where the training set grows over time
tscv = TimeSeriesSplit(n_splits=10)



# --- 3. XGBOOST GRID SEARCH ---
#print("Running XGBoost Grid Search...")
xgb_param_grid = {
    'max_depth': [3, 5],
    'min_child_weight': [1, 5],
    'gamma': [0.1, 0.2],
    'learning_rate': [0.01, 0.1],
    'n_estimators': [100, 200]
}

# 3. Use this 'tscv' object inside your GridSearchCV
xgb_grid = GridSearchCV(
    xgb.XGBClassifier(objective='binary:logistic', random_state=42),
    param_grid=xgb_param_grid,
    cv=tscv,
    scoring='neg_log_loss',
    n_jobs=-1
)

xgb_grid.fit(X_train, y_train)

# --- 4. LOGISTIC REGRESSION GRID SEARCH ---
#print("Running Logistic Regression Grid Search...")
# We use a Pipeline to ensure scaling happens inside the cross-validation folds
lr_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('lr', LogisticRegression(max_iter=1000))
])

lr_param_grid = {
    'lr__C': [0.01, 0.1, 1.0, 10.0], # Regularization strength
    'lr__penalty': ['l2']           # lbfgs solver only supports l2 or None
}

lr_grid = GridSearchCV(
    lr_pipe,
    param_grid=lr_param_grid,
    cv=tscv,
    scoring='neg_log_loss'
)

lr_grid.fit(X_train, y_train)

```

Na hodnotenie modelov boli použité viaceré metriky presnosť (accuracy), F1-skóre a log loss. Okrem samotnej klasifikácie bol kladený dôraz aj na kvalitu pravdepodobnostných výstupov.
Hodnotenie prebiehalo pri rôznych rozhodovacích thresholdoch (od 0.4 do 0.6), keďže štandardná hodnota 0.5 nemusí byť optimálna pre všetky modely ani pre daný problém.

V prípade logistickej regresie sa testovala rôzna sila regularizácie, zatiaľ čo pri XGBooste sa optimalizovali parametre ovplyvňujúce komplexnosť stromov, rýchlosť učenia a počet estimátorov. Optimalizácia prebiehala s cieľom minimalizovať log loss, čím sa podporilo lepšie kalibrovanie pravdepodobností.

Výsledky všetkých kombinácií modelov, hyperparametrov a thresholdov boli agregované a vizualizované pomocou heatmapy (obr. [-@fig-modeling-parameter]).
Z grafu je zrejmé, že výkon modelov je citlivý nielen na voľbu hyperparametrov, ale aj na rozhodovací threshold.
Pri niektorých konfiguráciách dochádza k výraznému zlepšeniu presnosti už pri miernom posune thresholdu od hodnoty 0.5.
Zároveň pozorujeme, že každý model výrazne outperformuje baseline model.

```{python}
#| echo: false
#| label: fig-modeling-parameter
#| fig-pos: 'H'
#| fig-cap: "Presnosť cez všetky hyperparametre a threshold (trénovacia množina)"

results_all_detailed = []
thresholds = [0.4, 0.45, 0.5, 0.55, 0.6]
searches = [('XGBoost', xgb_grid), ('LogisticRegression', lr_grid)]

for model_name, grid in searches:
    #print(f"Processing all iterations for {model_name}...")
    all_params = grid.cv_results_['params']

    # Use tqdm to track progress through hyperparameter combinations
    for i, params in enumerate(tqdm(all_params)):
        # 1. Recreate the model
        if model_name == 'XGBoost':
            current_model = xgb.XGBClassifier(**params, objective='binary:logistic', random_state=42)
        else:
            lr_params = {k.replace('lr__', ''): v for k, v in params.items()}
            current_model = Pipeline([
                ('scaler', StandardScaler()),
                ('lr', LogisticRegression(**lr_params, max_iter=1000))
            ])

        # 2. Manual OOF Cross-Validation (on X_train)
        oof_probs = []
        oof_true = []

        for train_idx, val_idx in tscv.split(X_train):
            X_f_train, X_f_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
            y_f_train, y_f_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

            current_model.fit(X_f_train, y_f_train)
            oof_probs.extend(current_model.predict_proba(X_f_val)[:, 1])
            oof_true.extend(y_f_val)

        oof_probs = np.array(oof_probs)
        oof_true = np.array(oof_true)

        # 3. Final Test Fit
        current_model.fit(X_train, y_train)
        test_probs = current_model.predict_proba(X_test)[:, 1]

        # 4. SAVE EVERY THRESHOLD RESULT
        for t in thresholds:
            # Calculate metrics for this specific threshold on BOTH sets
            train_metrics = get_metrics(oof_true, oof_probs, threshold=t)
            test_metrics = get_metrics(y_test, test_probs, threshold=t)

            entry = {
                'model_name': model_name,
                'iteration_index': i,
                'params': str(params),
                'threshold': t,
                # Training (CV) Results
                'cv_accuracy': train_metrics['accuracy'],
                'cv_f1': train_metrics['f1'],
                'cv_log_loss': train_metrics['log_loss'],
                # Test (Hold-out) Results
                'test_accuracy': test_metrics['accuracy'],
                'test_f1': test_metrics['f1'],
                'test_log_loss': test_metrics['log_loss'],
            }
            results_all_detailed.append(entry)

# Convert to DataFrame
all_runs_df = pd.DataFrame(results_all_detailed)

# We'll pivot the data to see Model/Params vs Threshold
# Let's look at Accuracy for this example
pivot_df = all_runs_df.pivot_table(
    index=['model_name', 'params'],
    columns='threshold',
    values='cv_accuracy'
)

plt.figure(figsize=(14, 8))
sns.heatmap(pivot_df, annot=True, cmap='YlGnBu', fmt=".3f")
#plt.title('Accuracy Across All Hyperparameters and Thresholds')
plt.ylabel('Konfigurácia Modelu')
plt.xlabel('Rozhodovací Threshold')
plt.tight_layout()
plt.show()

```

Na výber najlepšieho modelu bola použitá viackriteriálna optimalizácia, kde sa súčasne zohľadňovali tri metriky: presnosť (accuracy), F1-skóre a log loss.
Keďže cieľom bolo maximalizovať presnosť aj F1-skóre a zároveň minimalizovať log loss, bola hodnota log loss invertovaná, aby všetky metriky mali rovnaký optimalizačný smer.

Najskôr bola identifikovaná Pareto-optimálna množina modelov, teda modely, ktoré neboli dominované inými kandidátmi vo všetkých sledovaných metrikách.
Z tejto množiny bol následne zvolený „najlepší celkový model“ na základe Euklidovskej vzdialenosti od ideálneho bodu (1,1,1), ktorý reprezentuje hypotetický model s perfektnými hodnotami všetkých metrík.

Vybraný model predstavuje najlepší kompromis medzi presnosťou klasifikácie, vyváženosťou tried a kvalitou pravdepodobnostných predikcií. Po jeho výbere bol model finálne natrénovaný na celej trénovacej množine a vyhodnotený na testovacích dátach, kde dosiahol konzistentné výsledky potvrdzujúce jeho stabilitu a praktickú použiteľnosť.

```{python}
#| echo: false
#| fig-pos: 'H'

def find_3d_pareto(df):
    # Ensure our 'Higher is Better' metric exists
    df['cv_log_loss_inv'] = 1 - df['cv_log_loss']

    # Selection criteria: Accuracy, F1, and Inverse Log Loss
    cols = ['cv_accuracy', 'cv_f1', 'cv_log_loss_inv']
    data = df[cols].values
    pareto_indices = []

    for i, c1 in enumerate(data):
        is_dominated = False
        for j, c2 in enumerate(data):
            if i == j: continue
            # If c2 is better or equal in all AND strictly better in at least one
            if np.all(c2 >= c1) and np.any(c2 > c1):
                is_dominated = True
                break
        if not is_dominated:
            pareto_indices.append(i)

    return df.iloc[pareto_indices].copy()

pareto_3d_df = find_3d_pareto(all_runs_df)

# Display the table with parameters
# Note: 'params' column contains the hyperparameters from your GridSearch
pareto_summary = pareto_3d_df[[
    'model_name', 'threshold', 'cv_accuracy', 'cv_f1', 'cv_log_loss', 'params'
]].sort_values(by='cv_accuracy', ascending=False)

# Assuming pareto_3d_df exists from the previous step

# 1. Define the 'Perfect' coordinates
perfect_point = np.array([1.0, 1.0, 1.0])

# 2. Calculate distance for each candidate
def calculate_distance(row):
    model_point = np.array([
        row['cv_log_loss_inv'],
        row['cv_f1'],
        row['cv_accuracy']
    ])
    return np.linalg.norm(perfect_point - model_point)

pareto_3d_df['dist_to_perfect'] = pareto_3d_df.apply(calculate_distance, axis=1)

# 3. Find the winner
best_overall_model = pareto_3d_df.sort_values('dist_to_perfect').iloc[0]

print(f"Matematicky najlepší celkový model je:")
print(f"Model: {best_overall_model['model_name']}")
print(f"{best_overall_model['params']}")
print(f"Vzdialenosť k (1,1,1): {best_overall_model['dist_to_perfect']:.4f}")

print()
print(f"CV accuracy: {best_overall_model['cv_accuracy']}")
print(f"CV log_loss: {best_overall_model['cv_log_loss']}")
print(f"CV f1: {best_overall_model['cv_f1']}")

print()
print(f"Test accuracy: {best_overall_model['test_accuracy']}")
print(f"Test log_loss: {best_overall_model['test_log_loss']}")
print(f"Test f1: {best_overall_model['test_f1']}")

```

Výsledky vybraných modelov na testovacej množine sú znázornené na grafe [-@fig-modeling-testing].
Z grafu je zrejmé, že natrénované modely si zachovávajú porovnateľný výkon aj na doposiaľ nevidených dátach a dosahujú podobné hodnoty metrík ako na trénovacej množine.
Tento fakt naznačuje, že modely nevykazujú výrazné preučenie a disponujú dobrou schopnosťou generalizácie, čo potvrdzuje ich robustnosť a praktickú použiteľnosť pri predikcii výsledkov zápasov.

```{python}
#| echo: false
#| label: fig-modeling-testing
#| fig-pos: 'H'
#| fig-cap: "Presnosť cez všetky hyperparametre a threshold (testovacia množina)"
# We'll pivot the data to see Model/Params vs Threshold
# Let's look at Accuracy for this example
pivot_df = all_runs_df.pivot_table(
    index=['model_name', 'params'],
    columns='threshold',
    values='test_accuracy'
)

plt.figure(figsize=(14, 8))
sns.heatmap(pivot_df, annot=True, cmap='YlGnBu', fmt=".3f")
plt.title('Accuracy Across All Hyperparameters and Thresholds')
plt.ylabel('Model Configuration')
plt.xlabel('Decision Threshold')
plt.tight_layout()
plt.show()
```


### Vplyv príznakov

Na lepšie pochopenie správania natrénovaných modelov a interpretáciu ich rozhodnutí bola vykonaná analýza vplyvu jednotlivých príznakov pomocou metódy SHAP (SHapley Additive exPlanations).
Táto metóda umožňuje kvantifikovať príspevok každého vstupného príznaku k finálnej predikcii modelu a poskytuje konzistentné vysvetlenie založené na princípoch kooperatívnej teórie hier.

Pre oba vybrané modely XGBoost aj logistickú regresiu boli vypočítané SHAP hodnoty na trénovacej množine.
V prípade modelu XGBoost bol použitý TreeExplainer, ktorý je optimalizovaný pre stromové modely, zatiaľ čo pre logistickú regresiu bol aplikovaný LinearExplainer po predchádzajúcej štandardizácii vstupných dát.
Tento postup zabezpečuje porovnateľnosť váh jednotlivých príznakov a korektnú interpretáciu lineárneho modelu.

Na obrázku [-@fig-feature-importance] sú znázornené globálne dôležitosti príznakov vo forme stĺpcových SHAP súhrnných grafov pre oba modely.
Dĺžka jednotlivých stĺpcov reprezentuje priemernú absolútnu hodnotu SHAP, teda mieru, do akej daný príznak ovplyvňuje rozhodovanie modelu naprieč všetkými pozorovaniami.
Z výsledkov je zrejmé, že XGBoost model sa opiera najmä o príznak win_streak_diff súvisiaci s rozdiely medzi počtom po sebe vyhratých zápasov, zatiaľ čo pre model logistickej regresie je dôležitý príznak týkajúci sa počtu titulov.
Z pozorovania nám vyplýva, že jednotlivé novovzniknuté príznaky malo zmyseľ vytvoriť a zlepšili tak výkonnosť obidvoch modelov.  

Zároveň je možné pozorovať rozdiely medzi modelmi v spôsobe, akým využívajú dostupné informácie.
Zatiaľ čo XGBoost zachytáva nelineárne vzťahy a interakcie medzi príznakmi, logistická regresia kladie dôraz na menší počet dominantných, lineárne interpretovateľných premenných.
Táto analýza tak nielen zvyšuje dôveru v predikcie modelov, ale zároveň poskytuje cenný vhľad do faktorov, ktoré majú najväčší vplyv na výsledok tenisového zápasu.
```{python}
#| echo: false
#| label: fig-feature-importance
#| fig-pos: 'H'
#| fig-cap: "Vplyv jednotlivých parametrov na modely pomocou SHAP"
# We'll pivot the data to see Model/Params vs Threshold
# Let's look at Accuracy for this example
# 1. Calculate distance to perfect (1,1,1) for EVERY model in the full dataframe
perfect_point = np.array([1.0, 1.0, 1.0])

def calc_dist(row):
    point = np.array([row['cv_log_loss_inv'], row['cv_f1'], row['cv_accuracy']])
    return np.linalg.norm(perfect_point - point)

all_runs_df['dist_to_perfect'] = all_runs_df.apply(calc_dist, axis=1)

# 2. Extract the best XGBoost and the best Logistic Regression specifically
xgb_winner = all_runs_df[all_runs_df['model_name'] == 'XGBoost'].sort_values('dist_to_perfect').iloc[0]
lr_winner = all_runs_df[all_runs_df['model_name'] == 'LogisticRegression'].sort_values('dist_to_perfect').iloc[0]
# --- PREP XGBOOST ---
xgb_model = xgb.XGBClassifier(**eval(xgb_winner['params'])).fit(X_train, y_train)
explainer_xgb = shap.TreeExplainer(xgb_model)
shap_values_xgb = explainer_xgb.shap_values(X_train)

# --- PREP LOGREG ---
lr_params = {k.replace('lr__', ''): v for k, v in eval(lr_winner['params']).items()}
scaler = StandardScaler().fit(X_train)
X_train_scaled = pd.DataFrame(scaler.transform(X_train), columns=X_train.columns)
lr_model = LogisticRegression(**lr_params).fit(X_train_scaled, y_train)

explainer_lr = shap.LinearExplainer(lr_model, X_train_scaled)
shap_values_lr = explainer_lr.shap_values(X_train_scaled)

# --- VISUALIZE GLOBAL IMPORTANCE ---
fig, ax = plt.subplots(2, 1, figsize=(12, 20))

plt.sca(ax[0])
ax[0].set_title(f"XGBoost vplyv: {xgb_winner['params']}")
shap.summary_plot(shap_values_xgb, X_train, plot_type="bar", show=False)

plt.sca(ax[1])
ax[1].set_title(f"Logistická regresia vplyv: {lr_winner['params']}")
shap.summary_plot(shap_values_lr, X_train_scaled, plot_type="bar", show=False)

plt.tight_layout()
plt.show()

```



# Záver

Cieľom tohto projektu bolo analyzovať historické údaje o tenisových zápasoch a na ich základe vytvoriť modely schopné predpovedať výsledok zápasu ešte pred jeho odohraním. V súlade s metodikou CRISP-DM bol celý proces rozdelený do jednotlivých fáz od analýzy a predspracovania dát, cez modelovanie až po finálnu evaluáciu a interpretáciu výsledkov. Dôraz bol kladený nielen na samotnú presnosť predikcie, ale aj na robustnosť modelov a ich interpretovateľnosť.

Výsledky ukázali, že oba zvolené modely XGBoost aj logistická regresia sú schopné efektívne generalizovať a dosahovať porovnateľné výsledky na trénovacej aj testovacej množine.
To naznačuje, že modely netrpia výrazným preučením a dokážu zachytiť relevantné vzory prítomné v historických dátach.
Použitie časovo konzistentnej krížovej validácie zároveň zabezpečilo realistickejšie vyhodnotenie výkonu v kontexte predikcie budúcich zápasov.

Dôležitou súčasťou práce bola interpretácia modelov pomocou metódy SHAP, ktorá poskytla hlbší vhľad do vplyvu jednotlivých príznakov na rozhodovanie modelov.
Analýza potvrdila význam novovytvorených príznakov, ako napríklad rozdiel v sérii víťazstiev alebo počet získaných titulov, ktoré sa ukázali ako kľúčové faktory ovplyvňujúce výsledok zápasu. Rozdiely medzi modelmi zároveň poukázali na kontrast medzi schopnosťou XGBoostu zachytávať nelineárne vzťahy a jednoduchosťou a interpretovateľnosťou logistickej regresie.

Z praktického hľadiska práca ukazuje, že historické tenisové dáta môžu byť úspešne využité na predikciu výsledkov zápasov a že vhodná kombinácia feature engineeringu, modelovania a interpretácie vedie k zmysluplným a dôveryhodným výsledkom.
V práci sme postupne rozobrali všetky hlavné otázky a predostreli sme odpovede na ne.
Zároveň sa podarilo splniť kritéria, kde sme identifikovali kľúčové príznaky pri predikcií, vytvorili sme model s generalizačnou schopnosťou, ktorý mal lepšiu úspešnosť, ako na začiatku vytvorený baseline model.
Nakoniec sme odmerali stabitu a úspešnosť daných modelov pomocou metrík na testovacej množine, ktorá zohľadňuje očakávané výsledky pri nových dátach.